version: "3.9"  # optional since v1.27.0
services:

  nifi:
    image: apache/nifi
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
    volumes:
      - "./nifi-starter-nar/target/:/opt/nifi/nifi-current/extensions"
    ports:
      - "8443:8443"
      - "8080:8080"