x-user: &user admin
x-pwd: &pwd supersecret1

x-nifi-environment: &nifi-environment
  NIFI_WEB_HTTPS_PORT: 8443
  NIFI_CLUSTER_IS_NODE: "true"
  NIFI_ZK_CONNECT_STRING: "zookeeper:2181"
  NIFI_ELECTION_MAX_WAIT: "30 sec"
  NIFI_SENSITIVE_PROPS_KEY: "my-random-string"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
  SINGLE_USER_CREDENTIALS_USERNAME: *user
  SINGLE_USER_CREDENTIALS_PASSWORD: *pwd
  KEYSTORE_PASSWORD: supersecretkeystore
  TRUSTSTORE_PASSWORD: supersecrettruststore
  NIFI_CLUSTER_ADDRESS: "nifi-0"
  KEYSTORE_PATH: "/opt/certs/nifi-0/keystore.jks"
  TRUSTSTORE_PATH: "/opt/certs/nifi-0/truststore.jks"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi-toolkit:
    image: apache/nifi-toolkit:latest
    volumes:
      - ./nifi_certs:/opt/certs
    user: root
    entrypoint: ["bash", "-c", "/opt/nifi-toolkit/*/bin/tls-toolkit.sh standalone -o /opt/certs -n nifi-[0-1] -P supersecrettruststore -K supersecretkeystore -S supersecretkeystore; chown -R nifi:nifi /opt/certs"]

  nifi-0:
    image: apache/nifi:latest
    depends_on:
      nifi-toolkit:
        condition: service_completed_successfully
    volumes:
      - ./nifi_certs:/opt/certs
    ports:
      - 8443:8443
    environment:
      <<: *nifi-environment
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "sed -i 's/nifi.ui.banner.text=.*/nifi.ui.banner.text=nifi-0 /' conf/nifi.properties; ../scripts/start.sh"

  registry:
    image: apache/nifi-registry:latest
    ports:
      - 18080:18080
